spring:
  datasource:
    url: jdbc:postgresql://localhoste:5432/mercado
    username: postgres
    password: example
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
    baseline-on-migrate: true

